apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7InVzZXJuYW1lIjoiZGVuaXMtZ3JlbmllciIsInBhc3N3b3JkIjoiZ2hwX0VVak05bTBWNEdUVEJaR05jYTlETVNIbnl4R1dGZzFsQWxpSiIsImF1dGgiOiJaR1Z1YVhNdFozSmxibWxsY2pwbmFIQmZSVlZxVFRsdE1GWTBSMVJVUWxwSFRtTmhPVVJOVTBodWVYaEhWMFpuTVd4QmJHbEsifX19
kind: Secret
metadata:
  name: ghcr-secret
type: kubernetes.io/dockerconfigjson
